name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: yarn set version 3.2.1
    - run: yarn install
    - run: yarn build
    - run: yarn build-doc
    - run: yarn test

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.4.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@itseasy21/react-elastic-carousel@${{steps.changelog.outputs.version}}/file/README.md) [![Coverage Status](https://coveralls.io/repos/github/itseasy21/react-elastic-carousel/badge.svg?branch=main)](https://coveralls.io/github/itseasy21/react-elastic-carousel?branch=main) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@itseasy21/react-elastic-carousel)](https://www.npmjs.com/package/@itseasy21/react-elastic-carousel)

          ```bash
          npm i @itseasy21/react-elastic-carousel@${{steps.changelog.outputs.version}}
          ```
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./package.json